#!/usr/bin/env bash
#
# Deploy the PDFGate custom app to Make from version-controlled section files.
#
# Prerequisites:
#   npm install -g @makehq/cli        # or set MAKE=<runner>, e.g. "npx @makehq/cli"
#   make-cli login                    # OR export MAKE_API_KEY / MAKE_ZONE (see below)
#
# Auth (pick one):
#   1) make-cli login                 # stores credentials locally
#   2) export MAKE_API_KEY="..."      # CI-friendly
#      export MAKE_ZONE="eu2.make.com"
#
# Usage:
#   scripts/deploy.sh                 # create (if needed) + push every section
#
set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC="$ROOT/src"

# Make appends a random suffix to app names on create (e.g. "pdfgate-plqcq7").
# Override with APP_NAME=<actual name> to target an existing app; otherwise the
# script looks for an app labelled "$APP_LABEL" and falls back to creating one.
APP_NAME="${APP_NAME:-}"
APP_VERSION=1
APP_LABEL="PDFGate"
APP_DESC="Generate, process, and e-sign PDFs with PDFGate."
APP_THEME="#0055d4"
APP_LANG="en"
APP_AUDIENCE="global"

# Connection and webhook names are auto-generated by Make (they do not accept a
# --name flag), so they are resolved from `sdk-connections list` /
# `sdk-webhooks list` after creation (see first_name below).
CONNECTION_NAME=""
WEBHOOK_NAME=""

# Make CLI runner + global auth flags.
MAKE="${MAKE:-make-cli}"
AUTH=()
if [[ -n "${MAKE_API_KEY:-}" ]]; then AUTH+=(--api-key "$MAKE_API_KEY"); fi
if [[ -n "${MAKE_ZONE:-}" ]];    then AUTH+=(--zone "$MAKE_ZONE"); fi

mk() { "$MAKE" ${AUTH[@]+"${AUTH[@]}"} "$@"; }   # bash 3.2-safe empty-array expansion

# Run a create-style command but don't fail if the component already exists.
try_create() {
  if ! mk "$@" 2>/tmp/pdfgate-deploy.err; then
    if grep -qiE "already exists|duplicate|exists" /tmp/pdfgate-deploy.err; then
      echo "   (already exists, skipping create)"
    else
      cat /tmp/pdfgate-deploy.err >&2
      return 1
    fi
  fi
}

body() { cat "$1"; }   # read a section file

# Raw Make API call for the few operations the CLI does not expose
# (e.g. linking an instant-trigger module to its webhook). Resolves the API
# key/zone from MAKE_API_KEY / MAKE_ZONE or the make-cli login config.
make_api() {  # make_api <METHOD> <path> [json-body]
  local cfg="$HOME/.config/make-cli/config.json"
  local key="${MAKE_API_KEY:-}" zone="${MAKE_ZONE:-}"
  if [[ -z "$key" || -z "$zone" ]] && [[ -f "$cfg" ]]; then
    [[ -n "$key"  ]] || key="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1])).get("apiKey",""))' "$cfg")"
    [[ -n "$zone" ]] || zone="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1])).get("zone",""))' "$cfg")"
  fi
  [[ -n "$key" && -n "$zone" ]] || { echo "make_api: no Make credentials (run make-cli login or set MAKE_API_KEY/MAKE_ZONE)" >&2; return 1; }
  local curl_bin; curl_bin="$(command -v curl || echo /usr/bin/curl)"
  "$curl_bin" -sS -f -X "$1" "https://$zone/api/v2$2" \
    -H "Authorization: Token $key" -H "Content-Type: application/json" \
    ${3:+-d "$3"}
}

# Print the "name" of the first element of a JSON array on stdin.
first_name() { python3 -c 'import json,sys; d=json.load(sys.stdin); print(d[0]["name"] if d else "")'; }

# Find an existing app by label (Make suffixes names, so the label is stable).
find_app_by_label() {
  mk sdk-apps list | python3 -c '
import json,sys
label=sys.argv[1]
apps=[a for a in json.load(sys.stdin) if a.get("label")==label]
print(apps[0]["name"] if apps else "")' "$1"
}

# ── 1. App ──────────────────────────────────────────────────────────────────
if [[ -z "$APP_NAME" ]]; then
  APP_NAME="$(find_app_by_label "$APP_LABEL")"
fi
if [[ -z "$APP_NAME" ]]; then
  echo "▶ App: creating \"$APP_LABEL\""
  mk sdk-apps create \
    --name="pdfgate" --label="$APP_LABEL" --description="$APP_DESC" \
    --theme="$APP_THEME" --language="$APP_LANG" --audience="$APP_AUDIENCE" --private >/dev/null
  APP_NAME="$(find_app_by_label "$APP_LABEL")"
fi
[[ -n "$APP_NAME" ]] || { echo "Could not resolve app name" >&2; exit 1; }
echo "▶ App: $APP_NAME"
mk sdk-apps update --name="$APP_NAME" --version="$APP_VERSION" \
  --label="$APP_LABEL" --description="$APP_DESC" --theme="$APP_THEME" >/dev/null
if [[ -f "$ROOT/assets/icon-512.png" ]]; then   # Make requires a 512x512 PNG
  echo "   icon"
  mk sdk-apps set-icon --name="$APP_NAME" --version="$APP_VERSION" \
    --data-base64="$(base64 < "$ROOT/assets/icon-512.png" | tr -d '\n')" >/dev/null \
    || echo "   (icon upload failed, continuing)" >&2
fi

echo "   base + docs"
mk sdk-apps set-section --name="$APP_NAME" --version="$APP_VERSION" \
  --section=base --body="$(body "$SRC/base.imljson")"
mk sdk-apps set-docs --name="$APP_NAME" --version="$APP_VERSION" \
  --docs="$(body "$SRC/readme.md")"

# ── 2. Connection ───────────────────────────────────────────────────────────
CONNECTION_NAME="$(mk sdk-connections list --app-name="$APP_NAME" | first_name)"
if [[ -z "$CONNECTION_NAME" ]]; then
  mk sdk-connections create --app-name="$APP_NAME" --type=basic --label="PDFGate" >/dev/null
  CONNECTION_NAME="$(mk sdk-connections list --app-name="$APP_NAME" | first_name)"
fi
[[ -n "$CONNECTION_NAME" ]] || { echo "Could not resolve connection name" >&2; exit 1; }
echo "▶ Connection: $CONNECTION_NAME"
mk sdk-connections set-section --connection-name="$CONNECTION_NAME" \
  --section=api --body="$(body "$SRC/connections/pdfgate/api.imljson")"
mk sdk-connections set-section --connection-name="$CONNECTION_NAME" \
  --section=parameters --body="$(body "$SRC/connections/pdfgate/parameters.imljson")"

# ── 3. Modules ──────────────────────────────────────────────────────────────
# name | typeId | label | description | crud
# typeId: 4=action, 9=search, 10=instant trigger, 12=universal
# crud (Make "module action", optional): create | read | update | delete
MODULES=(
  "watchEnvelopeEvents|10|Watch envelope events|Triggers when an envelope is sent, completed, expired, voided or deleted, when a document in an envelope is completed, or when a recipient is activated or signs.|"
  "generatePdf|4|Generate a PDF|Generates a PDF from a URL or raw HTML.|create"
  "compressPdf|4|Compress a PDF|Compresses a PDF to reduce its file size.|"
  "flattenPdf|4|Flatten a PDF|Flattens an interactive PDF into a static, non-editable PDF.|"
  "extractFormData|4|Extract form data|Extracts form field values from a fillable PDF.|"
  "protectPdf|4|Protect a PDF|Encrypts a PDF and applies permission restrictions.|"
  "watermarkPdf|4|Watermark a PDF|Applies a text watermark to a PDF.|"
  "getDocument|4|Get a document|Returns information about a document.|read"
  "uploadFile|4|Upload a file|Uploads a PDF from a public URL so it can be used by other modules.|create"
  "deleteDocument|4|Delete a document|Deletes a document.|delete"
  "getEnvelope|4|Get an envelope|Returns information about an envelope.|read"
  "createEnvelope|4|Create an envelope|Creates a signing envelope from one or more documents.|create"
  "sendEnvelope|4|Send an envelope|Sends an envelope to its recipients.|"
  "makeApiCall|12|Make an API call|Performs an arbitrary authorized API call.|"
)

for entry in "${MODULES[@]}"; do
  IFS='|' read -r name typeId label desc crud <<< "$entry"
  dir="$SRC/modules/$name"
  echo "▶ Module: $name (type $typeId)"

  try_create sdk-modules create \
    --app-name="$APP_NAME" --app-version="$APP_VERSION" \
    --name="$name" --type-id="$typeId" --label="$label" --description="$desc" >/dev/null

  # Keep label/description in sync and link the connection.
  mk sdk-modules update --app-name="$APP_NAME" --app-version="$APP_VERSION" \
    --module-name="$name" --label="$label" --description="$desc" \
    --connection="$CONNECTION_NAME" >/dev/null

  # Module action (crud) is not exposed by the CLI.
  if [[ -n "$crud" ]]; then
    make_api PATCH "/sdk/apps/$APP_NAME/$APP_VERSION/modules/$name" "{\"crud\":\"$crud\"}" >/dev/null
  fi

  for section in api expect interface; do
    file="$dir/$section.imljson"
    [[ -f "$file" ]] || continue
    echo "   section: $section"
    mk sdk-modules set-section --app-name="$APP_NAME" --app-version="$APP_VERSION" \
      --module-name="$name" --section="$section" --body="$(body "$file")" >/dev/null
  done

  # Visible to users (required for approval; hidden modules are not reviewed/approved).
  mk sdk-modules set-public --app-name="$APP_NAME" --app-version="$APP_VERSION" \
    --module-name="$name" >/dev/null 2>&1 || true
done

# Modules that exist on Make but are retired (a published app cannot delete modules):
# keep them hidden so they are not reviewed/approved or shown to users.
for retired in downloadFile; do
  mk sdk-modules set-private --app-name="$APP_NAME" --app-version="$APP_VERSION" \
    --module-name="$retired" >/dev/null 2>&1 || true
done

# Module groups shown in the scenario builder.
echo "▶ Groups"
mk sdk-apps set-section --name="$APP_NAME" --version="$APP_VERSION" \
  --section=groups --body="$(body "$SRC/groups.imljson")" >/dev/null

# ── 4. Custom IML functions ─────────────────────────────────────────────────
# Make has disabled self-service custom IML functions platform-wide (403
# "admin permission 'apps edit' is needed"). They must be requested through
# Make's helpdesk / IML function form and are deployed by Make on your behalf.
# See https://developers.make.com/custom-apps-documentation/app-structure/iml-functions/custom-iml-functions-re-enablement
# This step therefore warns and continues instead of aborting the deploy.
FUNCTIONS_SKIPPED=()
for fn_dir in "$SRC"/functions/*/; do
  [[ -d "$fn_dir" ]] || continue
  fn="$(basename "$fn_dir")"
  echo "▶ Function: $fn"
  if ! try_create sdk-functions create \
      --app-name="$APP_NAME" --app-version="$APP_VERSION" --name="$fn"; then
    echo "   ⚠ skipped: custom IML functions are not enabled for this account (request via Make helpdesk)" >&2
    FUNCTIONS_SKIPPED+=("$fn")
    continue
  fi
  [[ -f "$fn_dir/code.js" ]] && mk sdk-functions set-code \
    --app-name="$APP_NAME" --app-version="$APP_VERSION" \
    --function-name="$fn" --code="$(body "$fn_dir/code.js")"
  [[ -f "$fn_dir/test.js" ]] && mk sdk-functions set-test \
    --app-name="$APP_NAME" --app-version="$APP_VERSION" \
    --function-name="$fn" --test="$(body "$fn_dir/test.js")"
done

# ── 5. Webhook (for the Watch Envelope Events instant trigger) ───────────────
WEBHOOK_NAME="$(mk sdk-webhooks list --app-name="$APP_NAME" | first_name)"
if [[ -z "$WEBHOOK_NAME" ]]; then
  mk sdk-webhooks create --app-name="$APP_NAME" --type=web --label="Envelope Events" >/dev/null
  WEBHOOK_NAME="$(mk sdk-webhooks list --app-name="$APP_NAME" | first_name)"
fi
[[ -n "$WEBHOOK_NAME" ]] || { echo "Could not resolve webhook name" >&2; exit 1; }
echo "▶ Webhook: $WEBHOOK_NAME"
for section in api parameters attach detach; do
  file="$SRC/webhooks/envelopeEvents/$section.imljson"
  [[ -f "$file" ]] || continue
  echo "   section: $section"
  mk sdk-webhooks set-section --webhook-name="$WEBHOOK_NAME" \
    --section="$section" --body="$(body "$file")"
done

# Link the webhook to the connection so attach/detach can use {{connection.apiKey}}
# (sdk-webhooks update only accepts --label).
echo "   link webhook → connection $CONNECTION_NAME"
make_api PATCH "/sdk/apps/webhooks/$WEBHOOK_NAME" \
  "{\"connection\":\"$CONNECTION_NAME\"}" >/dev/null

# Link the instant-trigger module to the webhook (not exposed by the CLI).
echo "   link watchEnvelopeEvents → $WEBHOOK_NAME"
make_api PATCH "/sdk/apps/$APP_NAME/$APP_VERSION/modules/watchEnvelopeEvents" \
  "{\"webhook\":\"$WEBHOOK_NAME\"}" >/dev/null

cat <<'DONE'

✅ Deploy complete.

Manual follow-up:
  • On the first real delivery, confirm the webhook can read the secret saved at
    attach time ({{webhook.secret}}) — signature verification depends on it.
  • Webhooks created in scenarios BEFORE the webhook→connection link existed have
    no connection; delete and re-create them in the scenario.

DONE
echo "Verify with:"
echo "  make-cli sdk-modules     list --app-name=$APP_NAME --app-version=$APP_VERSION"
echo "  make-cli sdk-connections list --app-name=$APP_NAME"
echo "  make-cli sdk-webhooks    list --app-name=$APP_NAME"

# ── Summary ─────────────────────────────────────────────────────────────────
echo
echo "✔ Deployed app '$APP_NAME' (connection: $CONNECTION_NAME, webhook: $WEBHOOK_NAME)"
if [[ ${#FUNCTIONS_SKIPPED[@]} -gt 0 ]]; then
  echo "⚠ Custom IML functions NOT deployed: ${FUNCTIONS_SKIPPED[*]}"
  echo "  Request enablement from Make (see comment in section 4), then re-run."
fi
